### ISSUE TITLE
Can't connect from public ip when the host is local. (Conflicts?)

### ISSUE THREAD

**Issue by XutaxKamay** [SoapboxRaceWorld/soapbox-race-core-old#11]
Title explains it, though it works when you use localhost, or the ip that the router give for LAN connection.
I'm not sure if it's my routeur bugging too atm.
Not sure what's wrong, but I get this login fail error (https://imgur.com/a/23AJ6) after launching by waiting some seconds it could be useful I guess if it could be fixed (So I don't have to write two ip on the serverlist to connect to my actual server), must be some conflicts while connecting, dunno. 

Otherwhise it works perfectly, thanks for this amazing project.

**Comment by LeoCodes21** [comment]
Hey! Make sure you're launching the server like this:

**(Make sure you have CDed into the `bin` directory)**
Linux:
```
./standalone.sh -b 0.0.0.0
```

Windows:
```
standalone.bat -b 0.0.0.0
```

Let me know if this helps.

**Comment by LeoCodes21** [comment]
One other thing to note: Make sure ports 8680 and 5222 are opened.

**Comment by LeoCodes21** [comment]
Closing because of no reply.

**Comment by XutaxKamay** [comment]
Ooops sorry. Been already some months, but the problem was dumb, it's just because I couldn't connect to my public ip. It was depending on some modems/routers, problems, sometimes they allow connection through it , and sometimes not.

My bad.
